WIP: Trying to add the gRPC server using tonic. Sadly getting this error:
error[E0046]: not all trait items implemented, missing: `BookSummaryStream`
   --> src/server.rs:24:1
    |
24  |   impl OrderbookAggregator for OrderbookAggregatorService {
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `BookSummaryStream` in implementation
    |
   ::: /home/extra/jason/software/mine/market_data_server_rust/target/debug/build/market_data_server_rust-182f766c60bcd229/out/orderbook.rs:144:9
    |
144 | /         type BookSummaryStream: futures_core::Stream<
145 | |                 Item = std::result::Result<super::Summary, tonic::Status>,
146 | |             >
147 | |             + Send
148 | |             + 'static;
    | |_____________________- `BookSummaryStream` from trait